name: 'build and check Python code'

on:

  workflow_dispatch:  # Allow manual triggering

  push:
    paths:
      - '.github/workflows/build-python.yaml'
      - 'requirements.txt'
      - 'pylint.config'
      - 'src/**'
      - 'test/**'

jobs:

  build_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - name: 'checkout code from repo'
      uses: actions/checkout@v5

    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: 'install dependencies'
      run: |
        python -m pip install --upgrade pip
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv tool install ruff@latest
        pip install -r requirements.txt

    - name: 'checking syntax of scripts'
      run: |
        python -m py_compile $(git ls-files '*.py')

    - name: 'analysing the code quality with pylint & ruff'
      run: |
        pylint --version
        pylint --rcfile=./pylint.config src test
        ruff --version
        ruff check .

    - name: 'running all Python tests'
      run: |
        echo "pwd: $(pwd)"
        ls -1 -alh
        export PYTHONPATH="$(pwd)/src:$(pwd)/test":$PYTHONPATH
        echo "PYTHONPATH:" $PYTHONPATH
        pytest --cov=./ --cov-report=xml

#    - name: Upload coverage reports to Codecov
#      uses: codecov/codecov-action@v4.0.1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        fail_ci_if_error: true
#        verbose: true